doctrine:
  orm:
    auto_mapping: true
    mappings:
      AppBundle:
        type: yaml
        dir: Resources/config/doctrine

AppBundle\Entity\PasswordHistory:
  type:  entity
  table: password_history
  repositoryClass: AppBundle\Repository\PasswordHistoryRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    user:
      targetEntity: AppBundle\Entity\User
      joinColumn:
        nullable: false
  fields:
    userId:
      column: user_id
      type: integer
      nullable: false
    password:
      column: password
      type: string
      nullable: false